clusterName: ""
organization: ""

# Add to this map the Apps that have a 'user-values' configmap defined in apps.yaml.
userConfig:
  cilium: true

apps:
  cilium:
    appName: cilium
    chartName: cilium
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cilium-app
    version: 0.6.1
  capi-node-labeler:
    appName: capi-node-labeler
    chartName: capi-node-labeler
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/capi-node-labeler-app
    version: 0.3.4
  certExporter:
    appName: cert-exporter
    chartName: cert-exporter
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-exporter
    version: 2.3.1
  certManager:
    appName: cert-manager
    chartName: cert-manager-app
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-manager-app
    version: 2.18.0
  coreDNS:
    appName: coredns
    chartName: coredns-app
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/coredns-app
    version: 1.13.0
  externalDns:
    appName: external-dns
    chartName: external-dns-app
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/external-dns-app
    version: 2.22.0
  gcp-compute-persistent-disk-csi-driver-app:
    appName: gcp-compute-persistent-disk-csi-driver
    chartName: gcp-compute-persistent-disk-csi-driver
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/giantswarm/gcp-compute-persistent-disk-csi-driver-app
    version: 0.5.0
  kubeStateMetrics:
    appName: kube-state-metrics
    chartName: kube-state-metrics
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/kube-state-metrics-app
    version: 1.14.1
  metricsServer:
    appName: metrics-server
    chartName: metrics-server-app
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/metrics-server-app
    version: 2.0.0
  netExporter:
    appName: net-exporter
    chartName: net-exporter
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/net-exporter
    version: 1.13.0
  nodeExporter:
    appName: node-exporter
    chartName: node-exporter-app
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/node-exporter-app
    version: 1.14.1
  vpa:
    appName: vertical-pod-autoscaler
    chartName: vertical-pod-autoscaler-app
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-app
    version: 2.5.2
  vpaCRD:
    appName: vertical-pod-autoscaler-crd
    chartName: vertical-pod-autoscaler-crd
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-crd
    version: 1.0.1
  workload-identity-operator-gcp:
    appName: workload-identity-operator-gcp
    chartName: workload-identity-operator-gcp
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/workload-identity-operator-gcp
    version: 0.5.0
  observabilityBundle:
    appName: observability-bundle
    chartName: observability-bundle
    catalog: default
    forceUpgrade: false
    inCluster: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/observability-bundle
    version: 0.1.8
