clusterName: ""
organization: ""

# Add to this map the Apps that have a 'user-values' configmap defined in apps.yaml.
userConfig:
  cilium: true
  externalDns:
    configMap:
      values: |
        provider: google
        serviceAccount:
          annotations:
            giantswarm.io/gcp-service-account: external-dns-app@{{ .Values.gcpProject }}.iam.gserviceaccount.com
        domainFilters:
          - {{ .Values.baseDomain }}
        txtOwnerId: giantswarm-{{ .Values.clusterName }}
        annotationFilter: giantswarm.io/external-dns=managed
        podLabels:
          giantswarm.io/gcp-workload-identity: enabled
        sources:
          - service
apps:
  cilium:
    appName: cilium
    chartName: cilium
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cilium-app
    version: 0.7.0
  capi-node-labeler:
    appName: capi-node-labeler
    chartName: capi-node-labeler
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/capi-node-labeler-app
    version: 0.3.4
  certExporter:
    appName: cert-exporter
    chartName: cert-exporter
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-exporter
    version: 2.3.1
  certManager:
    appName: cert-manager
    chartName: cert-manager-app
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-manager-app
    version: 2.19.0
  chartOperatorExtensions:
    appName: chart-operator-extensions
    chartName: chart-operator-extensions
    catalog: default
    enabled: true
    clusterValues:
      configMap: false
      secret: false
    dependsOn: prometheus-operator-crd
    namespace: giantswarm
    # used by renovate
    # repo: giantswarm/chart-operator-extensions
    version: 1.1.1
  coreDNS:
    appName: coredns
    chartName: coredns-app
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/coredns-app
    version: 1.14.2
  externalDns:
    appName: external-dns
    chartName: external-dns-app
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/external-dns-app
    version: 2.33.0
  gcp-compute-persistent-disk-csi-driver-app:
    appName: gcp-compute-persistent-disk-csi-driver
    chartName: gcp-compute-persistent-disk-csi-driver
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/giantswarm/gcp-compute-persistent-disk-csi-driver-app
    version: 0.5.0
  metricsServer:
    appName: metrics-server
    chartName: metrics-server-app
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/metrics-server-app
    version: 2.0.0
  netExporter:
    appName: net-exporter
    chartName: net-exporter
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/net-exporter
    version: 1.13.0
  nodeExporter:
    appName: node-exporter
    chartName: node-exporter-app
    catalog: default
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/node-exporter-app
    version: 1.15.0
  vpa:
    appName: vertical-pod-autoscaler
    chartName: vertical-pod-autoscaler-app
    catalog: default
    dependsOn: vertical-pod-autoscaler-crd
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-app
    version: 2.5.3
  vpaCRD:
    appName: vertical-pod-autoscaler-crd
    chartName: vertical-pod-autoscaler-crd
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-crd
    version: 1.0.1
  workload-identity-operator-gcp:
    appName: workload-identity-operator-gcp
    chartName: workload-identity-operator-gcp
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/workload-identity-operator-gcp
    version: 0.5.0
  observabilityBundle:
    appName: observability-bundle
    chartName: observability-bundle
    catalog: default
    forceUpgrade: false
    inCluster: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/observability-bundle
    version: 0.7.1
