{{- range $key, $value := .Values.apps }}
{{- $appName := .appName }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "{{ .forceUpgrade }}"
    {{- if .dependsOn }}
    # App is deployed in the org- namespace so the secret name is prefixed by the cluster-id
    app-operator.giantswarm.io/depends-on: {{ printf "%s-%s" $.Values.clusterID .dependsOn -}}
    {{- end }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    {{- if .inCluster }}
    app-operator.giantswarm.io/version: 0.0.0
    {{- end }}
  name: {{ $.Values.clusterName }}-{{ $appName }}
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: {{ .catalog }}
  name: {{ .chartName }}
  {{- if .inCluster }}
  namespace: {{ $.Release.Namespace }}
  kubeConfig:
    inCluster: true
  {{- else }}
  namespace: {{ .namespace }}
  kubeConfig:
    context:
      name: {{ $.Values.clusterName }}-admin@{{ $.Values.clusterName }}
    inCluster: false
    secret:
      name: {{ $.Values.clusterName }}-kubeconfig
      namespace: {{ $.Release.Namespace}}
  {{- end }}
  version: {{ .version }}
  config:
    configMap:
      name: {{ $.Values.clusterName }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  {{- with (get $.Values.userConfig $key) }}
  userConfig:
    configMap:
      name: {{ $.Values.clusterName }}-{{ $appName }}-user-values
      namespace: {{ $.Release.Namespace }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterName }}-cilium-user-values
  namespace: {{ $.Release.Namespace }}
data:
  values: |
    ipam:
      mode: kubernetes
    k8sServiceHost: api.{{ $.Values.baseDomain }}
    k8sServicePort: 443
    kubeProxyReplacement: strict
    hubble:
      relay:
        enabled: true
    defaultPolicies:
      enabled: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
